### GET ALL userS
GET http://localhost:3000/users HTTP/1.1


### GET SINGLE user
GET http://localhost:3000/users/2 HTTP/1.1



### CREATE user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
	"username": "user3"
}


### DELETE user
DELETE http://localhost:3000/users/3 HTTP/1.1


### UPDATE user
PUT http://localhost:3000/users/2 HTTP/1.1
Content-Type: application/json

{
	"username": "Sexy Cool Updated user"
}










### ADD SCORE
POST http://localhost:3000/scores HTTP/1.1
Content-Type: application/json

{
	"user_id": 2,
	"score": 500
}

### GET ALL SCORES
GET http://localhost:3000/scores HTTP/1.1


### GET ALL SCORES BY A user
GET http://localhost:3000/users/2/scores HTTP/1.1


### DELETE SCORE
DELETE http://localhost:3000/scores/6 HTTP/1.1


